### ISSUE TITLE
It is unable to accurately filter one or several requests and not print the logs. 

### ISSUE THREAD

**Issue by josercc** [assemmarwan/dio_http_formatter#14]
At present, there are several interfaces that require timed polling in our project. However, the printing of such interfaces can easily overwrite the logs. We hope to filter the logs of these timed polling interfaces. But after looking at the source code, it seems that it is not supported currently.

**Comment by assemmarwan** [comment]
@josercc If you would please share more details about the usecase? Some examples would be helpful to get the full picture

**Comment by assemmarwan** [comment]
@josercc I have added an improved functionality to control which request/responses to filter.

Please check it here #15 . And if you want to test it from pub.dev, it's available [here](https://pub.dev/packages/dio_http_formatter/versions/3.3.0-preview.1)
