### ISSUE TITLE
Build error with new dio-prev versions

### ISSUE THREAD

**Issue by paricleu** [assemmarwan/dio_http_formatter#2]
Building with the dio preview versions fails with the following error:
![image](https://user-images.githubusercontent.com/48349235/112619958-38571800-8e28-11eb-8670-899100c6cd90.png)

**Comment by baabale** [comment]
I am also having the same bug here.

**Comment by assemmarwan** [comment]
@paricleu @baabale Would you please confirm if this issue still persists with the current version (4.0.1) of Dio? I was unable to reproduce it 😬
