### ISSUE TITLE
Unhandled Exception: FormatException: Unexpected end of input (at character 1) - DIO 4.0.4 and dio_http_formatter 2.0.1

### ISSUE THREAD

**Issue by gabrielaraujoz** [assemmarwan/dio_http_formatter#5]
Hi there!

I'm having an issue with versions newer than 2.0.1 of dio_http_formatter, where I get this exception:

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: FormatException: Unexpected end of input (at character 1)
^
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:523:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:41:10)
#3      JsonDecoder.convert (dart:convert/json.dart:506:36)
#4      JsonCodec.decode (dart:convert/json.dart:157:41)
#5      jsonDecode (dart:convert/json.dart:96:10)
#6      HttpFormatter._getBody
package:dio_http_formatter/src/dio_http_formatter_base.dart:84
#7      HttpFormatter._prepareLog
package:dio_http_formatter/src/dio_http_formatter_base.dart:132
#8      HttpFormatter.onResponse
package:dio_http_formatter/src/dio_http_formatter_base.dart:57
#9      DioMixin.fetch._responseInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure>
package:dio/src/dio_mixin.dart:527
#10     DioMixin.checkIfNeedEnqueue (package:dio/src/d<…>
```

This won't happen if I roll the version back to 2.0.0. I have the newest version of dio in my project (4.0.4) and I could not understand why I am getting this error, since it doesn't point anywhere in my code (only inside the lib).

Could you please give me some light of what I could do to help fix this issue?

Thanks a lot!

**Comment by gabrielaraujoz** [comment]
ps. I'm receiving the data normally, the same data won't work with v^2.0.1 but will work with v2.0.0 :/

**Comment by gabrielaraujoz** [comment]
@assemmarwan I'll be glad to help you, do you have any idea of where I should start? 😄

**Comment by assemmarwan** [comment]
@gabrielaraujoz Would you please share the JSON that you are getting in the response? In addition, please share the platform you're using it on (Web, Desktop, Mobile) and the OS.

**Comment by gabrielaraujoz** [comment]
Hi there @assemmarwan, I'm sorry for the daley in replying.

Here's a call with v2.0.0:

```
flutter: │ 💡 ⤴ REQUEST ⤴
flutter: │ 💡
flutter: │ 💡 GET some link
flutter: │ 💡 X-User-Agent: 
flutter: │ 💡 Time-Zone:
flutter: │ 💡 Accept: 
flutter: │ 💡 Authorization: Bearer 
flutter: │ 💡
flutter: │ 💡 ⤵ RESPONSE [200/OK] [Time elapsed: 1012 ms]⤵
flutter: │ 💡
flutter: │ 💡 connection: [keep-alive]
flutter: │ 💡 cache-control: [no-store]
flutter: │ 💡 transfer-encoding: [chunked]
flutter: │ 💡 date: 
flutter: │ 💡 strict-transport-security: 
flutter: │ 💡 referrer-policy: 
flutter: │ 💡 x-permitted-cross-domain-policies: [none]
flutter: │ 💡 content-type:
flutter: │ 💡 x-xss-protection: 
flutter: │ 💡 x-request-id: 
flutter: │ 💡 x-download-options: 
flutter: │ 💡 x-runtime: 
flutter: │ 💡 etag: 
flutter: │ 💡 x-frame-options:
flutter: │ 💡 x-content-type-options: 
flutter: │ 💡 {
flutter: │ 💡   "data": { //JSON starts here

```

And here's a call with v2.1.0:
```
flutter: │ 💡 ⤴ REQUEST ⤴
flutter: │ 💡
flutter: │ 💡 GET some link
flutter: │ 💡 X-User-Agent: 
flutter: │ 💡 Time-Zone:
flutter: │ 💡 Accept: 
flutter: │ 💡 Authorization: Bearer 
flutter: │ 💡
flutter: │ 💡 {}
flutter: │ 💡
flutter: │ 💡 ⤵ RESPONSE [200/OK] [Time elapsed: 1012 ms]⤵
flutter: │ 💡
flutter: │ 💡 connection: [keep-alive]
flutter: │ 💡 cache-control: [no-store]
flutter: │ 💡 transfer-encoding: [chunked]
flutter: │ 💡 date: 
flutter: │ 💡 strict-transport-security: 
flutter: │ 💡 referrer-policy: 
flutter: │ 💡 x-permitted-cross-domain-policies: [none]
flutter: │ 💡 content-type:
flutter: │ 💡 x-xss-protection: 
flutter: │ 💡 x-request-id: 
flutter: │ 💡 x-download-options: 
flutter: │ 💡 x-runtime: 
flutter: │ 💡 etag: 
flutter: │ 💡 x-frame-options:
flutter: │ 💡 x-content-type-options: 
flutter: │ 💡 {
flutter: │ 💡   "data": { //JSON starts here

```

I had to anonymize the data but you'll notice an extra pair of {} in the beginning of the response of v2.1.0. I belive it has to do with the change made in v2.0.1, WDYT?

**Comment by assemmarwan** [comment]
Appreciate it, I'll go over it during the weekend 😄

**Comment by gabrielaraujoz** [comment]
Hi there @assemmarwan, how are you doing? Did we have any progress here? I thought about the exception logging and think we could optimize the error logging by analyzing the exception type..

We could pass the error to the _prepareLog method and analyze it's runtimeType. If it's a FormatException we could add the source in the log so that users can know exactly where the problem is.

I'll open a quick PR later with this piece of code for you to analyze, ok?

Thanks

**Comment by assemmarwan** [comment]
@gabrielaraujoz Apologies for the delay. Yeah sure, please open a PR and I'll review it 👍🏻

**Comment by assemmarwan** [comment]
Closing this for being stale
